#!/bin/bash

clear_last_line () {
  printf '\033[1A\033[K'
}

print_processing () {
  printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
}

print_success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
}

print_fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
}

print_info () {
  printf "\r  [\033[00;34mINFO\033[0m] %s\n" "$1"
}

run () {
  if ! $2 > /dev/null 2>&1; then
    clear_last_line
    print_fail "$1 failed! To see the details, run '$2' manually."
    exit 1
else
    clear_last_line
    print_success "$1 passed successfully."
    exit 0
fi
}

echo ""
print_info "Running pre-commit checks..."

# ===== LINT STAGE =====
print_processing "Running linter... Please wait."
run "Linter" "npm run lint:all"