#!/bin/bash

clear_last_line () {
  printf '\033[1A\033[K'
}

print_processing () {
  printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
}

print_success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
}

print_fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
}

print_info () {
  printf "\r  [\033[00;34mINFO\033[0m] %s\n" "$1"
}

print_empty_line () {
  echo ""
}

run_linter () {
  print_processing "Running linter... Please wait."
  LINT_COMMAND="npm run lint:all"
  if ! $LINT_COMMAND > /dev/null 2>&1; then
    clear_last_line
    print_fail "Linter failed! To see the details, run '$LINT_COMMAND' manually."
    print_empty_line
    exit 1
  else
    clear_last_line
    print_success "Linter passed successfully."
  fi
}

echo ""
print_info "Running pre-commit checks..."

# ===== STAGES =====
run_linter
# ==================

print_empty_line
exit 0